config/routes.rb
Rails.application.routes.draw do
  
  get '/movies' => 'movies#index'
  get '/movies/:id' => 'movies#show', as: :movie
  
  get '/actors' => 'actors#index'
  get '/actors/:id' => 'actors#show', as: :actor
  
  

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :parts
  has_many :movies, through: :parts
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :parts
  has_many :actors, through: :parts
  
end

app/models/part.rb
class Part < ActiveRecord::Base
  belongs_to :movie
  belongs_to :actor
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all
  end
  
  def show
    @actor = Actor.find(params[:id])
    @movies = @actor.movies
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
  
  def show
    @movie = Movie.find(params[:id])
    @actors = @movie.actors
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/actors/.index.html.erb
<div class="main actor-index">
      <div class="container">
        <div class="row">

          <!--
          To do: Loop through movies and display each one with this HTML
          <div class="actor col-xs-2">
            actor image goes here
            <h3> actor name goes here </h3>
            <p> actor bio goes here </p>
          </div>
          -->
          
      </div>
</div>

app/views/actors/.show.html.erb
<div class="main actor-show">
  <div class="container">
    
    <!-- Display an actor's info here -->
    <div class="actor">
      <!-- actor image -->
      <div class="info">
        <h3 class="actor-name">  </h3>
        <p class="actor-bio">  </p>
      </div>
    </div>

    <h2>Movies</h2>
    <!-- Display each movie's info here -->
    <div class="movie">
      <!-- movie image -->
      <h3 class="movie-title">  </h3>
      <p class="movie-release-year">  </p>
      <p class="movie-plot">  </p>
    </div>

  </div>
</div>

app/views/actors/index.html.erb
<div class="main actor-index">
      <div class="container">
        <div class="row">

          <!--
          To do: Loop through movies and display each one with this HTML
          -->
          <% @actors.each do |a| %>
          <div class="actor col-xs-2">
            <a href="<%= actor_path(a) %>"> <%= image_tag a.image %> </a>
            <h3> <%= a.first_name %> <%= a.last_name %> </h3>
            <p> <%= a.bio %> </p>
            
            
            <%= link_to 'Learn more', actor_path(a) %>
            
          </div>
          <% end %>
      </div>
</div>

app/views/actors/show.html.erb
<div class="main actor-show">
  <div class="container">
    
    <!-- Display an actor's info here -->
    <div class="actor">
      <!-- actor image -->
      <%= image_tag @actor.image %>
      <div class="info">
        <h3 class="actor-name"> <%= @actor.first_name %> <%= @actor.last_name %> </h3>
        <p class="actor-bio"> <%= @actor.bio %> </p>
      </div>
    </div>

    <h2>Movies</h2>
    <% @movies.each do |m| %>
    <div class="movie">
      <a href="<%= movie_path(m) %>"><%= image_tag m.image %></a>
      <h3 class="movie-title"> <%= m.title %> </h3>
      <p class="movie-release-year"> <%= m.release_year %> </p>
      <p class="movie-plot"> <%= m.plot %> </p>
    </div>
    <% end %>

  </div>
</div>

app/views/layouts/.application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bolt Movie Database</title>
    <link href='http://fonts.googleapis.com/css?family=Oxygen:300,400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="header">
      <div class="container">
        <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo.svg" height="40">
        <h1>Bolt Movie Database</h1>
      </div>
    </div>

    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bolt Movie Database</title>
    <link href='http://fonts.googleapis.com/css?family=Oxygen:300,400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="header">
      <div class="container">
        <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo.svg" height="40">
        <h1>Bolt Movie Database</h1>
      </div>
    </div>

    <%= yield %>

  </body>
</html>

app/views/movies/.index.html.erb
<div class="hero">
  <div class="container">
    <h2>Interstellar</h2>
    <p>Former NASA pilot Cooper (Matthew McConaughey) and a team of researchers travel across the galaxy to find out which of three planets could be mankind's new home.</p>
    <a href="#">Read More</a>
  </div>
</div>

<div class="main">
  <div class="container">
  <h2>Popular Films</h2>

    <!--
    To do: Loop through movies and display each one with this HTML
    <div class="movie">
      movie image goes here
      <h3> movie title goes here </h3>
      <p> movie release year goes here </p>
    </div>
    -->
      
  </div>
</div>

app/views/movies/.show.html.erb
<div class="main movie-show">
  <div class="container">
    <div class="movie">
      
      <!-- Display the movie's info here -->
      <div class="info">
        <!-- movie image -->
        <h3 class="movie-title">  </h3>
        <p class="movie-release-year">  </p>
        <p class="movie-plot">  </p>
      </div>
    </div>

    <h2>Cast</h2>
    <!-- Display each actor's info here -->
    <div class="actor">
      <!-- actor image -->
      <h3 class="actor-name">  </h3>
      <p class="actor-bio">  </p>
    </div>

  </div>
</div>

app/views/movies/index.html.erb
<div class="hero">
  <div class="container">
    <h2>Interstellar</h2>
    <p>Former NASA pilot Cooper (Matthew McConaughey) and a team of researchers travel across the galaxy to find out which of three planets could be mankind's new home.</p>
    <a href="#">Read More</a>
  </div>
</div>

<div class="main">
  <div class="container">
  <h2>Popular Films</h2>

    <!--
    To do: Loop through movies and display each one with this HTML
    -->
    <% @movies.each do |m| %>
    <div class="movie">
      <a href="<%= movie_path(m) %>"> <%= image_tag m.image %> </a>
      <h3> <%= m.title %> </h3>
      <p> <%= m.release_year %> </p>
      <%= link_to "Learn more", movie_path(m) %>
    </div>
    
    
    <% end %>
      
  </div>
</div>

app/views/movies/show.html.erb
<div class="main movie-show">
  <div class="container">
    <div class="movie">
      
      <!-- Display the movie's info here -->
      <%= image_tag @movie.image %>
      <div class="info">
        <!-- movie image -->
        <h3 class="movie-title"> <%= @movie.title %> </h3>
        <p class="movie-release-year"> <%= @movie.release_year %> </p>
        <p class="movie-plot"> <%= @movie.plot %> </p>
      </div>
    </div>

    <h2>Cast</h2>
    <!-- Display each actor's info here -->
    <% @actors.each do |a| %>
    <div class="actor">
      <a href="<%= actor_path(a) %>"><%= image_tag a.image %></a>
      <h3 class="actor-name"> <%= a.first_name %> <%= a.last_name %> </h3>
      <p class="actor-bio"> <%= a.bio %> </p>
    </div>
    
    <% end %>

  </div>
</div>